### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by clickinfinite** [darklynx/request-baskets#52]
Hi, Mr.Vladimir L. Thank you for sharing.  May I ask how to add and set an SSL certificate(Let's encrypt)?

**Comment by darklynx** [comment]
Hi,

I'm sorry for a late reply.

The idea of this application was to be as simple as possible, and support for SSL, though possible and quite easy to implement in Go, seemed to be an overkill for this service, because of the certificates management and configuration. You can easily make a mistake when dealing with security that may lead to the vulnerabilities in the software.

Instead it is recommended to run the service on the local network interface (default configuration) and place a professional proxy in front of it (e.g. Nginx, HA-Proxy, Lighttpd, Apache, etc.). Those are easy to configure and lots of them have native support for Let's encrypt automated configuration.

Our test service (https://rbaskets.in) uses Nginx as a proxy and [certbot](https://certbot.eff.org) to automate the certificates rotation.

Hope this helps, unless and most probably you have figured this out already.

Cheers,
Vladimir
