### ISSUE TITLE
Migrate to go modules

### ISSUE THREAD

**Issue by Jackymancs4** [darklynx/request-baskets#66]
Hello @darklynx 
I really like your implementation of a request bin.
I'm planning to add a some features that I need, meant mainly for personal use in my own fork but that you may like as well. 

Instrumental to this is updating the codebase to use the modern Go Modules (https://blog.golang.org/migrating-to-go-modules) instead of go packages.

I have a PR ready to be submitted if you are interested, the content of which can be seen https://github.com/Jackymancs4-Fork/request-baskets/tree/33895a324ebac4bc2086d7eb8778264a70667225

In that repo I replaced Travis CI with Github Actions worklows, with all tests passing.
If you're willing, this can be another issue.

Anyway, thank you.

**Comment by darklynx** [comment]
Hi @Jackymancs4 

Thank you for your interest and desire to contribute to this little project.

I really like your ideas about migrating to Go-modules (it was on my long awaiting list of to get to know better Go-modules and try them out with request baskets), since modules seem to be the officially promoted way to work with external dependencies in Go for quite a while already.

Moving to actions (or at least get to learn them) was also on my list :)

Unfortunately, I do not have much time at the moment to invest into this project, but I will gladly accept valuable PRs.

Thank you very much!
